name: EC2 Command

on:
  workflow_dispatch:

jobs:
  run_command:
    runs-on: ubuntu-latest

    steps:
      - name: Execute command on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: echo "Hello, World!"
